### ISSUE TITLE
32 bit build error

### ISSUE THREAD

**Issue by rox4d** [i-rinat/freshplayerplugin#368]
Hi can`t compile with 32bit version of ubuntu 16.04 with mesa (with dev debs) from Oibaf ppa (compilation works fine with 64bit  version OS, with same ppas).

[  0%] Built target git-revision
[  1%] Built target parson-obj
[ 27%] Built target shader_translator
[ 28%] Built target st
[ 29%] Built target link_check
[ 29%] Building C object src/CMakeFiles/freshwrapper-obj.dir/ppb_graphics3d.c.o
In file included from /INST/freshplayerplugin/src/ppb_graphics3d.c:38:0:
/INST/freshplayerplugin/3rdparty/angle/include/GLES2/gl2.h:38:26: error: conflicting types for 'GLintptr'
 typedef khronos_intptr_t GLintptr;
                          ^
In file included from /usr/include/GL/gl.h:2055:0,
                 from /usr/include/GL/glx.h:32,
                 from /INST/freshplayerplugin/src/glx.h:5,
                 from /INST/freshplayerplugin/src/ppb_graphics3d.h:27,
                 from /INST/freshplayerplugin/src/ppb_graphics3d.c:29:
/usr/include/GL/glext.h:469:19: note: previous declaration of 'GLintptr' was here
 typedef ptrdiff_t GLintptr;
                   ^
In file included from /INST/freshplayerplugin/src/ppb_graphics3d.c:38:0:
/INST/freshplayerplugin/3rdparty/angle/include/GLES2/gl2.h:39:26: error: conflicting types for 'GLsizeiptr'
 typedef khronos_ssize_t  GLsizeiptr;
                          ^
In file included from /usr/include/GL/gl.h:2055:0,
                 from /usr/include/GL/glx.h:32,
                 from /INST/freshplayerplugin/src/glx.h:5,
                 from /INST/freshplayerplugin/src/ppb_graphics3d.h:27,
                 from /INST/freshplayerplugin/src/ppb_graphics3d.c:29:
/usr/include/GL/glext.h:468:19: note: previous declaration of 'GLsizeiptr' was here
 typedef ptrdiff_t GLsizeiptr;
                   ^
src/CMakeFiles/freshwrapper-obj.dir/build.make:1166: recipe for target 'src/CMakeFiles/freshwrapper-obj.dir/ppb_graphics3d.c.o' failed
make[2]: *** [src/CMakeFiles/freshwrapper-obj.dir/ppb_graphics3d.c.o] Error 1
CMakeFiles/Makefile2:321: recipe for target 'src/CMakeFiles/freshwrapper-obj.dir/all' failed
make[1]: *** [src/CMakeFiles/freshwrapper-obj.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by i-rinat** [comment]
I think I lost one of the magic macros during structures shuffling. Should be back in https://github.com/i-rinat/freshplayerplugin/commit/842da14fed444663c60807bd7428d0d8599fcc62. Just tested in a 32-bit chroot. Looks like it's enough to fix the build.

**Comment by rox4d** [comment]
Thanks a lot.
