### ISSUE TITLE
Doesn't build on Ubuntu 12.04 any more

### ISSUE THREAD

**Issue by hotice** [i-rinat/freshplayerplugin#260]
The latest freshplayerplugin from Git can't be built on Ubuntu 12.04 any more - here's the error I get:
```
/«BUILDDIR»/freshplayerplugin-0.3.2+git20150831~webupd8~precise/src/config.c: In function 'fpp_config_initialize':
/«BUILDDIR»/freshplayerplugin-0.3.2+git20150831~webupd8~precise/src/config.c:151:9: error: implicit declaration of function 'config_error_type' [-Werror=implicit-function-declaration]
/«BUILDDIR»/freshplayerplugin-0.3.2+git20150831~webupd8~precise/src/config.c:151:40: error: 'CONFIG_ERR_PARSE' undeclared (first use in this function)
/«BUILDDIR»/freshplayerplugin-0.3.2+git20150831~webupd8~precise/src/config.c:151:40: note: each undeclared identifier is reported only once for each function it appears in
```
The complete build log can be found here: https://launchpadlibrarian.net/215966001/buildlog_ubuntu-precise-amd64.freshplayerplugin_0.3.2%2Bgit20150831~webupd8~precise_BUILDING.txt.gz

It used to work the last time I built it in my PPA, on August 21st.

**Comment by i-rinat** [comment]
Patches 1daa36a55bd4d3900b0487ddccf7c252c8e49052...9d987e2f88dd5eecc77a8d38220919871e1e0925 adds libconfuse to source tree, and change configuration file processing to use it, thus eliminating dependence on libconfig. Since there is no `libconfig-dev` in dependencies list, its different ABI shouldn't interfere compilation anymore. (I didn't try to build on Ubuntu 12, though).

**Comment by hotice** [comment]
It now builds successfully on Ubuntu 12.04, thanks!
