### ISSUE TITLE
failed to build

### ISSUE THREAD

**Issue by bewam** [i-rinat/freshplayerplugin#288]
Hello,

Thanks for your soft. Today I tried to build on ubuntu 15.10, I've got:

```
$ cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DWITH_HWDEC=0 ..
-- checking for optional dependencies
--   found libpulse, version 6.0 (optional)
--   found jack, version 1.9.10 (optional)
--   found soxr, version 0.1.1
-- Configuring done
-- Generating done
-- Build files have been written to: [...]/freshplayerplugin/build

$ make
[  0%] Built target git-revision
[  1%] Built target parson-obj
[  2%] Built target stringify_images
[  3%] Built target img-resource-srcs
[  5%] Built target img-resources
[  6%] Built target stringify_text
[  7%] Built target txt-resource-srcs
[ 10%] Built target txt-resources
[ 11%] Built target link_check
[ 12%] Building C object src/CMakeFiles/freshwrapper-obj.dir/ppb_flash_menu.c.o
[...]/freshplayerplugin/src/ppb_flash_menu.c:36:26: fatal error: version_info.h: No such file or directory
compilation terminated.
src/CMakeFiles/freshwrapper-obj.dir/build.make:951: recipe for target 'src/CMakeFiles/freshwrapper-obj.dir/ppb_flash_menu.c.o' failed
make[2]: *** [src/CMakeFiles/freshwrapper-obj.dir/ppb_flash_menu.c.o] Error 1
CMakeFiles/Makefile2:489: recipe for target 'src/CMakeFiles/freshwrapper-obj.dir/all' failed
make[1]: *** [src/CMakeFiles/freshwrapper-obj.dir/all] Error 2
Makefile:116: recipe for target 'all' failed
make: *** [all] Error 2
```

With a clean it's the same, but fails at 54%.
I don't really know C or C++, so I don't know if I'm wrong.

**Comment by i-rinat** [comment]
I've recently changed build scripts to include version information. Did you try to remove build directory and configure again? Previous configuration could interfere with a newer source.

**Comment by bewam** [comment]
Unfortunately, removing build directory didn't help. We obtain exactly the same error:
```
[ 72%] Building C object src/CMakeFiles/freshwrapper-obj.dir/ppb_flash_menu.c.o
[...]/freshplayerplugin/src/ppb_flash_menu.c:36:26: fatal error: version_info.h: No such file or directory
compilation terminated.
src/CMakeFiles/freshwrapper-obj.dir/build.make:951: recipe for target 'src/CMakeFiles/freshwrapper-obj.dir/ppb_flash_menu.c.o' failed
make[2]: *** [src/CMakeFiles/freshwrapper-obj.dir/ppb_flash_menu.c.o] Error 1
CMakeFiles/Makefile2:581: recipe for target 'src/CMakeFiles/freshwrapper-obj.dir/all' failed
make[1]: *** [src/CMakeFiles/freshwrapper-obj.dir/all] Error 2
Makefile:116: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by i-rinat** [comment]
Fixed in 5c5ba9540c3ca1398c1b817e48bb52da8a6fb8c8.

Forgot to add `${CMAKE_BINARY_DIR}` to include directories. It was there only in `WITH_HWDEC=1` configurations.

**Comment by bewam** [comment]
I'd better remove this option too, I've quickly read the instructions. :)
In any case, it had been built smoothly. :+1:
