### ISSUE TITLE
Fifa 16 webapp doesn't work

### ISSUE THREAD

**Issue by worldowner** [i-rinat/freshplayerplugin#274]
Arch Linux
Flash 19.0.0.185
freshplugin from GIT compiled 15 mins ago

Laptop with Intel GPU.

When I try to enter FUT webapp (https://www.easports.com/pl/fifa/ultimate-team/web-app) I get following errors:
NOT SANDBOXED
[fresh] [warning] ppb_var_var_to_utf8, 'var' is not a string, (0)
[fresh   992] not implemented: PPB_OpenGLES2VertexArrayObject;1.0
[fresh   992] not implemented: PPB_OpenGLES2DrawBuffers(Dev);1.0
Vector smash protection is enabled.
2015-10-02 17:15:49: basic_code_modules.cc:70: ERROR: Module /usr/lib/libsystemd.so.0 could not be stored
2015-10-02 17:15:49: basic_code_modules.cc:70: ERROR: Module /usr/lib/libnss_myhostname.so.2 could not be stored
2015-10-02 17:15:49: basic_code_modules.cc:70: ERROR: Module /usr/lib/firefox/components/libdbusservice.so could not be stored
2015-10-02 17:15:49: basic_code_modules.cc:70: ERROR: Module /usr/lib/firefox/components/libmozgnome.so could not be stored
OpenGL vendor string:                   Intel Open Source Technology Center
OpenGL renderer string:                 Mesa DRI Intel(R) Haswell Mobile 
OpenGL version string:                  3.3 (Core Profile) Mesa 11.0.2
OpenGL shading language version string: 3.30
Driver:                                 Intel
GPU class:                              Haswell
OpenGL version:                         3.3
GLSL version:                           3.30
Mesa version:                           11.0.2
X server version:                       1.17.2
Linux kernel version:                   4.2.2
Requires strict binding:                yes
GLSL shaders:                           yes
Texture NPOT support:                   yes
Virtual Machine:                        no

**Comment by i-rinat** [comment]
Could you describe what does "doesn't work" mean? What do you expect to happen, and what actually happens?

I don't have appropriate EA account to check myself.

**Comment by worldowner** [comment]
The area where flash app should be desplayed is all black. When I click on it I get usual flash menu (with flash version etc) so something gets loaded.

**Comment by worldowner** [comment]
It is the same issue as #275 (3D support not working in Firefox 41.0.1). FUT Webapp works with 3D support disabled in freshwrapper.conf.

**Comment by i-rinat** [comment]
Same as for #275, possible solutions are (one of the):
* reconfigure with `cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DWITH_GLES2=0 ..` and then rebuild;
* downgrade Mesa to 11.0.1 (or older);
* upgrade Mesa to version from git;
* add `enable_3d=0` to `~/.config/freshwrapper.conf` (will cause higher CPU usage).

**Comment by worldowner** [comment]
I have this issue again:
arch linux
mesa 11.0.4

git version of freshplugin wrapper, latest pepper flash

2015-11-07 00:19:15: basic_code_modules.cc:70: ERROR: Module /usr/lib/firefox/liblgpllibs.so could not be stored
2015-11-07 00:19:15: basic_code_modules.cc:70: ERROR: Module /usr/lib/libsystemd.so.0 could not be stored
2015-11-07 00:19:15: basic_code_modules.cc:70: ERROR: Module /usr/lib/firefox/components/libdbusservice.so could not be stored

I can't debug it as plugin-continer is not on process list.

**Comment by i-rinat** [comment]
> I can't debug it as plugin-continer is not on process list.

Are there any other messages printed if you start browser from terminal emulator? I think that plugin container either crashes early, or just fails to load plugin at all.

Try to enable automatic core dumps, perhaps there is some information could be extracted from them. (As far as I know, Archlinux uses systemd's facilities to manage core dumps: https://wiki.archlinux.org/index.php/Core_dump)

**Comment by i-rinat** [comment]
Hello?

**Comment by worldowner** [comment]
It's hard to debug, because it happens only on my laptop (with Intel graphics) that I use rarely and happens from time to time. When I'll get something I will post it here.

**Comment by worldowner** [comment]
You can close the issue. It's working fine since some time. Thank you.
